### ISSUE TITLE
Restore fails

### ISSUE THREAD

**Issue by MyOwnClone** [Antaris/CompileModuleExample#1]
Either in VSCode or Visual Studio, when running restore, I get: 

Errors in c:\work\github\CompileModuleExample\project.json
    Package Microsoft.CodeAnalysis.CSharp 1.0.0 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package Microsoft.CodeAnalysis.CSharp 1.0.0 supports:
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
    Package Microsoft.CodeAnalysis.Common 1.0.0 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package Microsoft.CodeAnalysis.Common 1.0.0 supports:
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
    Package System.Collections.Immutable 1.1.36 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package System.Collections.Immutable 1.1.36 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
    Package System.Reflection.Metadata 1.0.21 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package System.Reflection.Metadata 1.0.21 supports: portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
    One or more packages are incompatible with DNXCore,Version=v5.0.
ERROR: Error: Command failed: dotnet restore "c:\work\github\CompileModuleExample\project.json"

Errors in c:\work\github\CompileModuleExample\project.json
    Package Microsoft.CodeAnalysis.CSharp 1.0.0 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package Microsoft.CodeAnalysis.CSharp 1.0.0 supports:
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
    Package Microsoft.CodeAnalysis.Common 1.0.0 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package Microsoft.CodeAnalysis.Common 1.0.0 supports:
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
    Package System.Collections.Immutable 1.1.36 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package System.Collections.Immutable 1.1.36 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
    Package System.Reflection.Metadata 1.0.21 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package System.Reflection.Metadata 1.0.21 supports: portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
    One or more packages are incompatible with DNXCore,Version=v5.0.

**Comment by Antaris** [comment]
Hi,
Sadly the CompileModule feature is no longer support (this was built on pre-RC1 code). The whole CompileModule approach was taken away because they are hoping to build something directly into Roslyn to handle this, so for now CompileModule is dead in the water.
The restore issues are because the older packages are no longer on the feeds and those packages that have been updated no longer support the "dnxcore50" TFM.
